on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake libbluetooth-dev libsdl-dev freeglut3-dev
      - name: Dependencies (MacOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew update
          brew ls --versions cmake && brew upgrade cmake || brew install cmake
      - name: Build
        run: | 
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
      
